# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: name1
      POSTGRES_USER: ellie
      POSTGRES_DB: resume
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
